### ISSUE TITLE
Uncaught TypeError: Object [object Object] has no method 'on' 

### ISSUE THREAD

**Issue by shinytoyrobots** [ryanto/ember-google-analytics#1]
Hits this on line 28 for me, when loaded after ember.js but prior to the GA snippet.

**Comment by ryanto** [comment]
Hello, what version of Ember are you using?

**Comment by calebjacob** [comment]
I ran into the same problem running 1.1.2. I upgraded to Ember's 1.2 release and it works great.

**Comment by shinytoyrobots** [comment]
Ah, was on 1.1.2. Will check on 1.2 release (just upgraded).
